name: tugaskelompok
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


  flutter_svg: ^2.0.10
  intl: ^0.18.1
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.12
  firebase_core: ^2.27.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.5
  shared_preferences: ^2.2.2
  http: ^1.4.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  page_transition: ^2.0.9
  lottie: ^3.1.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 

flutter:
  uses-material-design: true
  assets:
    - "assets/lottie/Animation - 1751188217430.json"
    - "assets/google.png"


